import { useState } from 'react';
import { Link, NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { ShieldCheck, LayoutDashboard, Package, Plus, LocateFixed, Inbox, Bell, UserRound, LogOut, Search, Menu, X, ChevronDown, ArrowUpRight, ScanLine, CircleHelp, ShieldAlert, Clock3, CheckCircle2, Ban, History } from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';
import { initials, Modal } from '../ui/shared';
export function Logo() { return <span className="logo"><span className="logo-mark"><ShieldCheck size={23}/></span><span>FraudShield<span className="logo-ai">AI</span></span></span>; }
const userNav = [{ to: '/user/dashboard', label: 'Overview', icon: LayoutDashboard }, { to: '/user/shipments', label: 'My shipments', icon: Package }, { to: '/user/create-shipment', label: 'Create shipment', icon: Plus }, { to: '/user/track', label: 'Track shipment', icon: LocateFixed }, { to: '/user/inbox', label: 'Inbox', icon: Inbox }, { to: '/user/alerts', label: 'Alerts', icon: Bell }, { to: '/user/profile', label: 'My profile', icon: UserRound }];
const adminNav = [{ to: '/admin/dashboard', label: 'Command center', icon: LayoutDashboard }, { to: '/admin/packages', label: 'All packages', icon: Package }, { to: '/admin/packages/pending', label: 'Awaiting approval', icon: Clock3 }, { to: '/admin/packages/suspicious', label: 'Suspicious', icon: ShieldAlert }, { to: '/admin/packages/on-hold', label: 'On hold', icon: Clock3 }, { to: '/admin/packages/approved', label: 'Approved', icon: CheckCircle2 }, { to: '/admin/packages/blocked', label: 'Blocked', icon: Ban }, { to: '/admin/audit', label: 'Audit history', icon: History }];
export function AppLayout() {
  const { user, logout } = useAuth(); const admin = user!.role === 'ADMIN'; const nav = admin ? adminNav : userNav; const [mobile, setMobile] = useState(false); const [help, setHelp] = useState(false); const [query, setQuery] = useState(''); const navigate = useNavigate(); const location = useLocation();
  const current = nav.find(n => n.to === location.pathname)?.label || (location.pathname.includes('/review/') ? 'Package investigation' : location.pathname.includes('/users/') ? 'Customer intelligence' : 'Workspace');
  return <div className={`app-shell ${admin ? 'admin-theme' : ''}`}>
    {mobile && <button className="sidebar-shade" aria-label="Close navigation" onClick={() => setMobile(false)}/>}
    <aside className={`sidebar ${mobile ? 'open' : ''}`}>
      <Link to={admin ? '/admin/dashboard' : '/user/dashboard'} className="brand-link"><Logo/></Link>
      <button className="workspace-switch" onClick={() => navigate(admin ? '/login' : '/admin/login')}><span className="workspace-icon">{admin ? <ScanLine size={19}/> : <Package size={19}/>}</span><span><strong>{admin ? 'Risk operations' : 'Shipping workspace'}</strong><small>{admin ? 'Investigation console' : 'Personal account'}</small></span><ChevronDown size={15}/></button>
      <span className="nav-label">{admin ? 'OPERATIONS' : 'WORKSPACE'}</span>
      <nav aria-label="Main navigation">{nav.map(n => <NavLink key={n.to} to={n.to} end className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`} onClick={() => setMobile(false)}><n.icon size={19}/><span>{n.label}</span>{n.label === 'Create shipment' && <span className="nav-shortcut">ï¼‹</span>}</NavLink>)}</nav>
      <div className="sidebar-bottom"><div className="sidebar-note"><ShieldCheck size={21}/><strong>{admin ? 'Evidence before action.' : 'A little extra peace of mind.'}</strong><p>{admin ? 'Every review keeps the full story. Every decision leaves a record.' : 'Every shipment, protected by a smarter layer of care.'}</p><button onClick={() => setHelp(true)}>{admin ? 'Review guidelines' : 'How we protect you'} <ArrowUpRight size={14}/></button></div><button className="nav-item" onClick={() => setHelp(true)}><CircleHelp size={18}/>Help & support</button><div className="sidebar-user"><span className="avatar">{initials(user!.name)}</span><div><strong>{user!.name}</strong><small>{admin ? 'Fraud analyst' : user!.company || 'Personal account'}</small></div><button className="logout-btn" onClick={() => { logout(); navigate(admin ? '/admin/login' : '/login'); }}><LogOut size={16}/><span>Log out</span></button></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="icon-btn mobile-menu" aria-label="Open navigation" onClick={() => setMobile(true)}><Menu size={22}/></button><span className="breadcrumb-root">{admin ? 'Operations' : 'Workspace'}</span><span className="breadcrumb-slash">/</span><strong>{current}</strong></div><div className="topbar-right"><form className="global-search" onSubmit={e => { e.preventDefault(); navigate(admin ? `/admin/packages?q=${encodeURIComponent(query)}` : `/user/track?id=${encodeURIComponent(query)}`); }}><Search size={16}/><input aria-label="Search shipments" placeholder="Search shipmentsâ€¦" value={query} onChange={e => setQuery(e.target.value)}/><kbd>â†µ</kbd></form><span className="demo-pill"><span/>Demo workspace</span><Link className="icon-btn notification-button" aria-label={admin ? 'View audit activity' : 'View alerts'} to={admin ? '/admin/audit' : '/user/alerts'}><Bell size={19}/><i/></Link><Link className="avatar avatar-small" to={admin ? '/admin/dashboard' : '/user/profile'} aria-label="Your profile">{initials(user!.name)}</Link></div></header>
    <main className="main-content" key={location.pathname}><Outlet/></main><footer className="app-footer"><span>Â© {new Date().getFullYear()} FraudShield AI</span><span><span className="live-dot"/>Interactive demo Â· fictitious data</span></footer></div>
    {help && <Modal title={admin ? 'Review with context' : 'Shipping, with confidence'} close={() => setHelp(false)}><p className="muted">{admin ? 'Risk is an indicator, not proof. Review the shipment, account history and supporting evidence before taking action. Add a clear reason to every decision.' : 'Track your packages, manage your shipments and find updates in your inbox. Razorpay handles payments. Risk checks decide whether shipments need email verification or admin review.'}</p><div className="info-box">This is a local workflow demonstration. New bookings use the saved LightGBM model; seeded bookings use sample scores. Razorpay and email are real services when configured. Booking records stay in this browser, and carrier dispatch is simulated.</div><button className="btn primary full" onClick={() => setHelp(false)}>Got it <X size={15}/></button></Modal>}
  </div>;
}
