import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Check, ShieldCheck, PackageCheck, Copy, Pencil } from 'lucide-react';
import { ShipmentProvider, useShipment } from '../contexts/ShipmentContext';
import { useAuth } from '../contexts/AuthContext';
import { shipmentApi } from '../services/api/shipmentApi';
import { ShipmentSummary } from '../components/shipment/ShipmentSummary';
import { ShipmentStepper, steps } from '../components/shipment/ShipmentStepper';
import { ShippingForm, PackagingForm, CollectionForm, PackageDetailsForm, ProtectionForm, PaymentForm } from '../components/shipment/Forms';
import { PageHeading, Modal, Spinner, money, useToast } from '../components/ui/shared';
import type { Shipment } from '../types';
export function CreateShipmentPage() { const { user } = useAuth(); return <ShipmentProvider key={user!.id}><Wizard/></ShipmentProvider>; }
const subtitles = ['A great journey starts with the right details.', 'Find the right fit for what you’re sending.', 'Your doorstep or ours. Choose what works for you.', 'Help us understand what’s inside.', 'A little extra confidence for your delivery.', 'Choose how you’d like to pay. This one’s on demo mode.', 'One last look before your package starts its journey.'];
function Wizard() {
  const { user } = useAuth(); const { draft: d, reset } = useShipment(); const [step, setStep] = useState(0); const [accepted, setAccepted] = useState(false); const [modal, setModal] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [created, setCreated] = useState<Shipment | null>(null); const toast = useToast();
  const go = (n: number) => { setStep(n); setAccepted(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  async function confirm() { if (busy) return; setBusy(true); setError(''); try { const s = await shipmentApi.create(d, user!); setCreated(s); reset(); setModal(false); toast('Shipment created. Your demo payment is complete.'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (created) return <div className="success-page panel"><div className="success-orbit"><PackageCheck size={44}/></div><p className="eyebrow">THE NEXT CHAPTER STARTS HERE</p><h1>Your shipment is booked.</h1><p className="muted">{created.draft.sender.city} → {created.draft.receiver.city}<br/>Your demo payment of {money(created.price.total)} was successful. No money was charged.</p><div className="tracking-receipt"><small>YOUR TRACKING ID</small><strong>{created.id}</strong><button className="icon-btn" aria-label="Copy tracking ID" onClick={async () => { try { await navigator.clipboard.writeText(created.id); toast('Tracking ID copied.'); } catch { toast('Copy the tracking ID displayed above.'); } }}><Copy size={18}/></button></div><p className="field-hint">Your booking is awaiting its shipment review. Updates will appear in your inbox.</p><div className="button-row"><Link className="btn primary" to={`/user/track?id=${created.id}`}>Track shipment <ArrowRight size={17}/></Link><button className="btn secondary" onClick={() => { setCreated(null); go(0); }}>Send another package</button></div></div>;
  const components = [<ShippingForm/>, <PackagingForm/>, <CollectionForm/>, <PackageDetailsForm/>, <ProtectionForm/>, <PaymentForm/>];
  return <><PageHeading eyebrow="LET’S GET IT MOVING" title="Create a shipment" description="A few details now. A smooth journey ahead."><span className="draft-saved"><Check size={15}/>Draft saved in this browser</span></PageHeading><ShipmentStepper step={step} go={go}/><div className="wizard-layout"><form className="panel wizard-form" onSubmit={e => { e.preventDefault(); if (step < 6) go(step + 1); else setModal(true); }}><div className="section-head"><div><span className="eyebrow">STEP {step + 1} OF 7</span><h2>{steps[step]}</h2><p className="muted">{subtitles[step]}</p></div></div><div className="wizard-body">{step < 6 ? components[step] : <><div className="review-grid">{[{ title: 'Sender', text: `${d.sender.name}\n${d.sender.address}\n${d.sender.city}, ${d.sender.state} ${d.sender.pin}\n${d.sender.phone}`, step: 0 }, { title: 'Receiver', text: `${d.receiver.name}\n${d.receiver.address}\n${d.receiver.city}, ${d.receiver.state} ${d.receiver.pin}\n${d.receiver.phone}`, step: 0 }, { title: 'Package', text: `${d.packaging} · ${d.weight} kg\n${d.description}\n${d.quantity} item(s) · ${money(d.value)}`, step: 3 }, { title: 'Collection & payment', text: `${d.collection}\n${d.collection === 'Pickup' ? `${d.pickupDate} · ${d.pickupTime}` : d.dropoff}\n${d.payment} · simulated payment`, step: 2 }].map(c => <div className="review-detail" key={c.title}><div><h3>{c.title}</h3><button type="button" className="icon-btn" aria-label={`Edit ${c.title}`} onClick={() => go(c.step)}><Pencil size={15}/></button></div><p>{c.text}</p></div>)}</div><label className="checkbox-label"><input required type="checkbox" checked={accepted} onChange={e => setAccepted(e.target.checked)}/><span>I’ve checked the shipment details and understand that this is a demo booking with a simulated payment.</span></label></>}</div><div className="wizard-footer"><button type="button" className="btn secondary" disabled={step === 0} onClick={() => go(step - 1)}><ArrowLeft size={16}/>Back</button><span className="muted">{step + 1} / 7</span><button className="btn primary">{step === 6 ? 'Confirm shipment' : 'Continue'}<ArrowRight size={16}/></button></div></form><ShipmentSummary/></div>{modal && <Modal title="Ready for its next journey?" close={() => !busy && setModal(false)}><p className="muted">Confirm your {d.sender.city} → {d.receiver.city} shipment and simulate a {d.payment} payment of <strong>{money(shipmentApi.quote(d).total)}</strong>.</p><div className="info-box"><ShieldCheck size={20}/>This creates a demo booking. No real payment or pickup will take place.</div>{error && <p className="form-error" role="alert">{error}</p>}<div className="button-row end"><button className="btn secondary" disabled={busy} onClick={() => setModal(false)}>Keep editing</button><button className="btn primary" disabled={busy} onClick={confirm}>{busy ? <Spinner/> : <Check size={16}/>}Confirm & create</button></div></Modal>}</>;
}
