import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Search, Download } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { shipmentApi } from '../services/api/shipmentApi';
import { useAsync, Loading, ErrorState, PageHeading, useToast } from '../components/ui/shared';
import { ShipmentTable } from '../components/shipment/ShipmentTable';
export function ShipmentsPage() { const { user } = useAuth(); const { data, loading, error, reload } = useAsync(() => shipmentApi.list(user!.id)); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All shipments'); const [page, setPage] = useState(1); const toast = useToast(); if (loading) return <Loading/>; if (error || !data) return <ErrorState message={error} retry={reload}/>; const filtered = data.filter(s => `${s.id} ${s.draft.sender.city} ${s.draft.receiver.city}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All shipments' || s.delivery === status || s.status === status));
  function exportCsv() { const csv = ['Tracking ID,Origin,Destination,Delivery,Review status', ...filtered!.map(s => [s.id, s.draft.sender.city, s.draft.receiver.city, s.delivery, s.status].map(v => `"${v.replaceAll('"', '""')}"`).join(','))].join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const a = document.createElement('a'); a.href = url; a.download = 'fraudshield-shipments.csv'; a.click(); URL.revokeObjectURL(url); toast('Shipment list exported.'); }
  return <><PageHeading eyebrow="EVERY JOURNEY" title="My shipments" description="From booked to delivered. Keep an eye on every package."><button className="btn secondary" onClick={exportCsv}><Download size={16}/>Export</button><Link className="btn primary" to="/user/create-shipment"><Plus size={16}/>Create shipment</Link></PageHeading><section className="panel"><div className="filter-row"><label className="search-field"><Search size={17}/><input aria-label="Search your shipments" placeholder="Search tracking ID or city…" value={query} onChange={e => { setQuery(e.target.value); setPage(1); }}/></label><select aria-label="Filter shipment status" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}>{['All shipments', 'Created', 'Picked Up', 'In Transit', 'Out for Delivery', 'Delivered', 'Delayed', 'On Hold', 'Blocked'].map(s => <option key={s}>{s}</option>)}</select></div><ShipmentTable shipments={filtered.slice((page - 1) * 10, page * 10)}/><div className="pagination"><span>{filtered.length} shipment{filtered.length === 1 ? '' : 's'} · Page {page} of {Math.max(1, Math.ceil(filtered.length / 10))}</span><div><button className="btn secondary small" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><button className="btn secondary small" disabled={page * 10 >= filtered.length} onClick={() => setPage(page + 1)}>Next</button></div></div></section></>;
}
