import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Package, Truck, CheckCircle2, Bell, ArrowRight, Plus, LocateFixed, ShieldCheck, ArrowUpRight, CalendarDays } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { shipmentApi } from '../services/api/shipmentApi';
import { userApi } from '../services/api/userApi';
import { PageHeading, StatCard, useAsync, Loading, ErrorState, date } from '../components/ui/shared';
import { ShipmentTable } from '../components/shipment/ShipmentTable';
export function UserDashboard() {
  const { user } = useAuth(); const { data, loading, error, reload } = useAsync(async () => ({ shipments: await shipmentApi.list(user!.id), notices: await userApi.notices(user!.id) }), [user!.id]); const [tracking, setTracking] = useState(''); const navigate = useNavigate();
  if (loading) return <Loading/>; if (error || !data) return <ErrorState message={error} retry={reload}/>;
  const { shipments, notices } = data;
  return <><PageHeading eyebrow="YOUR SHIPPING, SIMPLIFIED" title={`A good day to send, ${user!.name.split(' ')[0]}.`} description="A little overview of everything you have on the move."><span className="date-chip"><CalendarDays size={15}/>{date(new Date().toISOString(), true)}</span><Link className="btn primary" to="/user/create-shipment"><Plus size={17}/>Create shipment</Link></PageHeading>
    <section className="stat-grid"><StatCard label="Active shipments" value={shipments.filter(s => s.delivery !== 'Delivered' && s.status !== 'Blocked').length} foot="On their way to something good" icon={Package}/><StatCard label="In transit" value={shipments.filter(s => s.delivery === 'In Transit').length} foot="Moving across the network" icon={Truck} color="blue"/><StatCard label="Delivered" value={shipments.filter(s => s.delivery === 'Delivered').length} foot="Safely at their destination" icon={CheckCircle2} color="purple"/><StatCard label="Unread updates" value={notices.filter(n => !n.read).length} foot="A few things to catch up on" icon={Bell} color="amber"/></section>
    <section className="dashboard-feature-grid"><div className="track-hero"><div className="hero-copy"><span className="eyebrow"><LocateFixed size={15}/>CLOSER WITH EVERY MILE</span><h2>Where’s your<br/>next good thing?</h2><p>Follow your package, from the first mile to the last.</p><form className="track-input" onSubmit={e => { e.preventDefault(); if (tracking.trim()) navigate(`/user/track?id=${encodeURIComponent(tracking.trim())}`); }}><Package size={18}/><input aria-label="Tracking ID" required placeholder="Enter your tracking ID" value={tracking} onChange={e => setTracking(e.target.value)}/><button className="btn primary" aria-label="Track shipment"><ArrowRight size={19}/></button></form><small>Try one of your recent shipment IDs below.</small></div><div className="route-art" aria-hidden="true"><svg viewBox="0 0 330 270"><defs><pattern id="dots" width="18" height="18" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#b9d9ce"/></pattern></defs><rect width="330" height="270" fill="url(#dots)"/><path d="M75 203C10 118 230 176 168 64S295 22 286 111" fill="none" stroke="#5f9d89" strokeWidth="2" strokeDasharray="5 6"/><circle cx="75" cy="203" r="7" fill="#147963"/><circle cx="286" cy="111" r="7" fill="#147963"/><path d="m133 105 61-29 62 29-62 31z" fill="#d4b993"/><path d="m133 105 61 31v70l-61-31z" fill="#bea17b"/><path d="m194 136 62-31v70l-62 31z" fill="#e1c6a1"/><path d="m161 91 61 31v24l-13 6v-24l-60-30z" fill="#f1debd"/><path d="m206 169 29-14v14l-29 14z" fill="#faf4e8"/></svg><span className="route-art-label origin">Chennai <span className="live-dot"/></span><span className="route-art-label destination"><CheckCircle2 size={13}/>Mumbai</span><span className="parcel-protection"><ShieldCheck size={14}/>In safe hands</span></div></div>
    <div className="quick-card"><span className="quick-card-icon"><ShieldCheck size={26}/></span><span className="eyebrow">BUILT-IN PEACE OF MIND</span><h3>A smarter layer<br/>of protection.</h3><p>Thoughtful checks help keep your shipments and your account safe, every step of the way.</p><Link to="/user/alerts">View your updates <ArrowUpRight size={17}/></Link><div className="quick-card-footer"><span className="live-dot"/>Your workspace is up to date</div></div></section>
    <section className="panel"><div className="section-head"><div><h2>Recent shipments <span className="count-pill">{shipments.length}</span></h2><p className="muted">Every journey, in one place.</p></div><Link className="text-link" to="/user/shipments">View all shipments <ArrowRight size={15}/></Link></div><ShipmentTable shipments={shipments.slice(0, 5)}/></section>
    <section className="bottom-grid"><Link to="/user/create-shipment" className="action-card"><span className="action-icon"><Package size={21}/></span><div><h3>Something to send?</h3><p>Book a pickup. We’ll take it from here.</p></div><ArrowUpRight size={21}/></Link><Link to="/user/inbox" className="action-card"><span className="action-icon amber"><InboxIcon/></span><div><h3>You’re in the loop.</h3><p>Find delivery updates and messages in your inbox.</p></div><ArrowUpRight size={21}/></Link></section>
  </>;
}
function InboxIcon() { return <Bell size={21}/>; }
