import { createContext, useContext, useEffect, useRef, useState, useCallback, type ReactNode, type ComponentType } from 'react';
import { Check, X, PackageSearch, ArrowUpRight, AlertCircle, LoaderCircle } from 'lucide-react';
import { subscribeStore } from '../../services/api/store';
export const money = (n: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);
export const date = (s: string, full = false) => new Date(s).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', ...(full ? { year: 'numeric' as const } : {}) });
export const initials = (s: string) => s.split(' ').map(x => x[0]).slice(0, 2).join('');
export function Badge({ children, tone = '' }: { children: ReactNode; tone?: string }) { return <span className={`badge ${tone || String(children).toLowerCase().replaceAll(' ', '-')}`}><span className="badge-dot"/>{children}</span>; }
export function RiskBadge({ score, level }: { score: number | null; level: string }) { return <div className="risk-badge"><span className={`risk-number ${level.toLowerCase()}`}>{score ?? '—'}</span><Badge>{level}</Badge></div>; }
export function PageHeading({ eyebrow, title, description, children }: { eyebrow?: string; title: string; description: string; children?: ReactNode }) { return <div className="page-heading"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1><p className="muted">{description}</p></div><div className="heading-actions">{children}</div></div>; }
export function StatCard({ label, value, foot, icon: Icon, color = 'teal' }: { label: string; value: number | string; foot: string; icon: ComponentType<{ size?: number }>; color?: string }) { return <div className="stat-card"><div className="stat-top"><span>{label}</span><span className={`stat-icon ${color}`}><Icon size={19}/></span></div><strong>{value}</strong><small><ArrowUpRight size={13}/>{foot}</small></div>; }
export function Empty({ title = 'Nothing here just yet', message = 'Try changing your filters, or check back later.', children }: { title?: string; message?: string; children?: ReactNode }) { return <div className="empty"><div className="empty-icon"><PackageSearch size={30}/></div><h3>{title}</h3><p>{message}</p>{children}</div>; }
export function Loading() { return <div className="loading" role="status" aria-label="Loading"><div className="skeleton heading-skeleton"/><div className="stat-grid">{[1, 2, 3, 4].map(i => <div key={i} className="skeleton stat-skeleton"/>)}</div><div className="skeleton table-skeleton"/><span className="sr-only">Loading…</span></div>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div className="error-state" role="alert"><AlertCircle/><h3>Something needs attention</h3><p>{message}</p>{retry && <button className="btn secondary" onClick={retry}>Try again</button>}</div>; }
export function Spinner() { return <LoaderCircle size={17} className="spin"/>; }
export function useAsync<T>(fetcher: () => Promise<T>, deps: unknown[] = []) {
  const [data, setData] = useState<T | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [version, setVersion] = useState(0);
  useEffect(() => { setLoading(true); }, deps);
  useEffect(() => { let active = true; setError(''); fetcher().then(d => { if (active) setData(d); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [...deps, version]);
  const reload = useCallback(() => setVersion(v => v + 1), []);
  useEffect(() => subscribeStore(reload), [reload]);
  return { data, error, loading, reload, setData };
}
const ToastContext = createContext<(message: string) => void>(() => {});
export function ToastProvider({ children }: { children: ReactNode }) { const [messages, setMessages] = useState<{ id: string; text: string }[]>([]); const notify = useCallback((text: string) => { const id = crypto.randomUUID(); setMessages(m => [...m, { id, text }]); setTimeout(() => setMessages(m => m.filter(x => x.id !== id)), 4500); }, []); return <ToastContext.Provider value={notify}>{children}<div className="toasts" aria-live="polite">{messages.map(m => <div className="toast" key={m.id}><Check size={18}/><span>{m.text}</span><button className="icon-btn" aria-label="Dismiss notification" onClick={() => setMessages(all => all.filter(x => x.id !== m.id))}><X size={16}/></button></div>)}</div></ToastContext.Provider>; }
export const useToast = () => useContext(ToastContext);
export function Modal({ title, children, close }: { title: string; children: ReactNode; close: () => void }) {
  const ref = useRef<HTMLDivElement>(null); const closeRef = useRef(close); closeRef.current = close;
  useEffect(() => { const before = document.activeElement as HTMLElement; const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; ref.current?.focus(); const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') closeRef.current(); if (e.key === 'Tab') { const els = ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input, select, textarea, a[href]'); if (!els?.length) return; const first = els[0], last = els[els.length - 1]; if (e.shiftKey && (document.activeElement === first || document.activeElement === ref.current)) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && (document.activeElement === last || document.activeElement === ref.current)) { e.preventDefault(); first.focus(); } } }; document.addEventListener('keydown', onKey); return () => { document.removeEventListener('keydown', onKey); document.body.style.overflow = old; before?.focus(); }; }, []);
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" ref={ref} tabIndex={-1}><div className="section-head"><h2 id="modal-title">{title}</h2><button className="icon-btn" aria-label="Close dialog" onClick={close}><X size={20}/></button></div>{children}</div></div>;
}
